application: jontitan-cs373-wc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: wc.app
libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest